[package]
name = "dotfm"
version = "0.4.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.226", features = ["derive"] }
shellexpand = "3.1.1"
thiserror = "2.0.17"
toml = "0.9.6"
